apiVersion: v1
kind: Service
metadata:
  name: service-clusterip
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 #pod port
  selector:
    app: nginx
