apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: service-nodeport
spec:
  ports:
  - port: 80
    nodePort: 32229 # if you reach this port outside the cluster it will be routed to this service
    protocol: TCP
    targetPort: 80 # same as containerPort from the deployment
  selector:
    app: nginx
  type: NodePort

