apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  type: LoadBalancer
  
