apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
    service: webserver
  name: busybox
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
    - image: busybox
      name: busybox
      args:
      - echo
      - "bananinha" 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
