apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-secrets
  labels:
    app: deployment-with-secrets
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template: 
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - image: nginx
          name: nginx-pod
          env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: password
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.3
              memory: 64Mi
