apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS0xLmRvY2tlci5pbyI6IHsKCQkJImF1dGgiOiAiZEdWbllXODZaR05yY2w5d1lYUmZhbkl6WlVsMFVGVmllVlptY0ZCTVNIVkViR3h2YnpNeVRHazAiCgkJfQoJfQp9
