apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: my-pvc
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-storage
  selector:  
    matchLabels:
      storage: nfs
