apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-exporter-daeamonset
  name: node-exporter-daeamonset
spec:
  selector:
    matchLabels:
      app: node-exporter-daeamonset
  template:
    metadata:
      labels:
        app: node-exporter-daeamonset
    spec:
      hostNetwork: true #it enables the network from the nodes instead of the container network
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          hostPort: 9100
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys 
