apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: nginx-deployment #deployment app
  name: nginx-deployment #deployment iname
  namespace: batata
spec:
  replicas: 8
  revisionHistoryLimit: 10
  selector:
    matchLabels:  
      app: nginx-deployment #this deployment will take care of the pods that match this name
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # One more pod will be create, from the new replicaSet, in order to lauch the new version
      maxUnavailable: 1 # Number of POD's to be killed in the rollout process
  # The configs above arei about the deployment, the configs bellow are about the pod    
  template:
    metadata:
      labels: 
        app: nginx-deployment
    spec:
      containers:
        - image: nginx:1.17.0
          name: nginx #pods name
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests: 
              cpu: 0.3
              memory: 64Mi
