apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-secrets-with-configmap
  labels:
    app: nginx-tls
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-tls
  template:
    metadata:
      labels:
        app: nginx-tls
    spec:
      containers:
      - name: nginx-tls
        image: nginx
        ports:
          - containerPort: 80 
          - containerPort: 443
        volumeMounts: 
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-tls
            mountPath: /etc/nginx/tls
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-tls
        secret:
          secretName: web-service-tls-secret
          items:
            - key: tls.crt
              path: kubernetes-certificate.crt
            - key: tls.key
              path: kubernetes-test.key
