apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-tls
  name: deployment-secrets-with-configmap
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-tls
status:
  loadBalancer: {}
